+
valkiriy/yandex-react pull request #5
Opened 2022-11-04 11:18 UTC by valkiriy

2022-11-04 12:29 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **очень хорошую** работу по типизации вашего проекта. Тем не менее, для успешной сдачи вам необходимо внимательно изучить комментарии, оставленные в рамках ревью и **исправить** следующие важные моменты:

- В проекте присутствует большое количество **отключений линтера** с помощью директивы `// @ts-ignore`, в основном из-за хуков, в том числе ваших кастомных, которые не были типизированы (пример: хук useUser). Такой подход считается плохой практикой и должен использоваться только в крайних случаях, когда по-другому нельзя объяснить TS. как и с чем это кушать. Поэтому, вам следует добавить отсутствующую типизацию в файлы/хуки/функции, где она отсутствует и убрать данные директивы;
- Использование типа `any` в большинстве случае **нецелесообразно**, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными. Для исправления типизации используйте возможности вашей IDE по автоматическому выявлению типов у пропсов компонентов, а также применяйте типизацию на всех доступных переменных (например хукам), к которым в дальнейшем идет обращение. (см. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-04 12:29 UTC, randomroot commented on src/services/utils.ts
> +export function setCookie(name: string, value: any, props: any) {
🔴 **Нужно исправить:**

Использование типа `any` в большинстве случае нецелесообразно, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными. 

Например, здесь параметры можно типизировать следующим образом:

```ts
  name: string,
  value: string,
  props: { [key: string]: string | number | Date | boolean } = {}
```

2022-11-04 12:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.tsx
>      const {bun, ingredients} = useSelector(state => state.burger)
🔴 **Нужно исправить:**

Типизацию хуков из `Redux` следует также обозначить, не следует заглушать тайпскрипт командой `ts-ignore`. Пример типизации вы можете найти в документации: https://redux.js.org/usage/usage-with-typescript#define-typed-hooks

2022-11-04 12:29 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.tsx
> +    let user:any = useUser();
Типизация в вашем проекте должна также покрывать и ваши собственные кастомные хуки, что обеспечить стабильность работы проекта, а также полностью отказаться от использования чистого JS, поэтому вам следует типизировать хук `useUser` и не использовать для обозначения его переменных тип `any`

2022-11-04 12:29 UTC, randomroot commented on src/components/burger-constructor/constructor-item.tsx
> +            const clientOffset: any = monitor.getClientOffset()
🟡 **Можно улучшить:**

Используйте возможности вашей IDE для определения типизации методов и переменных из внешних библиотек и нативных элементов, чтобы уменьшить использования `any` в проекте:

![image](https://user-images.githubusercontent.com/15111821/199967085-c150318b-3cbc-4f66-965f-8c9574f05e83.png)

Тогда данную строку кода можно заменить следующим образом:

```ts
import { XYCoord } from "react-dnd";
...
const clientOffset: XYCoord | null = monitor.getClientOffset()
```

2022-11-04 12:29 UTC, randomroot commented on src/components/app/app.tsx
>      const background = location.state && location.state.background;
🔴 **Нужно исправить:**

У хука `useLocation` есть возможность передать, какое внутреннее состояние он может содержать, что позволит отказаться от заглушения TS: 

```ts
const location = useLocation<{ background: boolean}>();
const background = location.state && location.state.background;
```

2022-11-04 12:29 UTC, randomroot commented on src/components/modal/modal.tsx
> +const modalRoot: any = document.getElementById("modal");
🟡 **Можно улучшить:**

Используйте возможности вашей IDE для определения типизации методов и переменных из внешних библиотек и нативных элементов, чтобы уменьшить использования `any` в проекте:

![image](https://user-images.githubusercontent.com/15111821/199968920-41758fa5-6d71-40c6-b09e-74406f1b5647.png)

2022-11-04 12:29 UTC, randomroot commented on src/components/modal/modal.tsx
> +export function Modal ({ children, onClose }: IModal) {
🟡 **Можно улучшить:**

Чтобы не типизировать пропс `children` самостоятельно, можно воспользоваться удобным интерфейсом, встроенным в React и, если заменить функцию на константу, то можно лаконично описать:

```ts
import { FC } from 'react'

interface IModal {
    onClose: () => void
}

export const Modal: FC<IModal> = ({ children, onClose }) { ... }
```

2022-11-06 09:44 UTC, valkiriy commented on src/services/utils.ts
> +export function setCookie(name: string, value: any, props: any) {
+

2022-11-06 09:45 UTC, valkiriy commented on src/components/app/app.tsx
>      const background = location.state && location.state.background;
+

2022-11-06 09:48 UTC, valkiriy commented on src/components/modal/modal.tsx
> +export function Modal ({ children, onClose }: IModal) {
+

2022-11-06 09:49 UTC, valkiriy commented on src/components/modal/modal.tsx
> +const modalRoot: any = document.getElementById("modal");
+

2022-11-06 09:54 UTC, valkiriy commented on src/components/burger-constructor/constructor-item.tsx
> +            const clientOffset: any = monitor.getClientOffset()
+

2022-11-07 08:12 UTC, randomroot approved these changes
**Работа принята**, желаю вам хорошего дня и успехов в дальнейшем обучении! 🐈

2022-11-07 08:12 UTC, randomroot commented on src/components/app/app.tsx
> +    const background = (location.state as any)?.background;
🟡 **Можно улучшить:**

Не следует здесь теперь использовать `any`, т.к. выше вы типизировали уже состояние и `background` автоматически получит тип `boolean`:

![image](https://user-images.githubusercontent.com/15111821/200255171-d878d36e-daac-4dfe-b27e-614b022d6e61.png)

2022-11-07 09:15 UTC, valkiriy commented on src/components/app/app.tsx
> +    const background = (location.state as any)?.background;
ниже в jsx была ошибка если сделать как у вас, получилось только так ее исправить

2022-11-07 09:15 UTC, merged